title: Grenoble Adventure Club
author:
  name: Binnette
description: >
  Hiking, via ferrata, canoe, geocaching, canyoning, ski, snowshoeing,
  climbing, cinema, parties and much more!

show_excerpts: false # set to true to show excerpts on the homepage
show_downloads: false
#url: https://binnette.github.io/GAC/


minima:
  skin: solarized
  # generate social links in footer
  social_links:
    github: Binnette/Gac
    telegram: GrenobleAdventureClub
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - About.md

# Build settings
plugins:
  - jekyll-remote-theme

remote_theme: oinam/oinam-jekyll
#remote_theme: jekyll/minima
#remote_theme: pages-themes/slate@v0.2.0
