# Site settings
title: Grenoble Adventure Club
description: Hike, ski, climbing, cinema, parties and much more!
url: https://binnette.github.io/GAC/
show_downloads: false

# Build settings
theme: minima

header_pages:
  - About.md

minima:
  skin: solarized
  social_links:
    github: Binnette
    telegram: GrenobleAdventureClub
